services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins

networks:
  jenkins:
volumes:
  jenkins-data:
    external: true
